create schema soccer;

CREATE TABLE SOCCER.COUNTRY(
Country_Name VARCHAR(20),
Population  DECIMAL(10,2) NOT NULL,
No_of_Worldcup_won INT,
Manager VARCHAR (20),
CONSTRAINT CNAME_PK PRIMARY KEY(Country_Name)
);

CREATE TABLE SOCCER.PLAYERS(
Player_id INT,
Name VARCHAR (40) NOT NULL,
Fname VARCHAR (20) NOT NULL,
Lname VARCHAR (35) NOT NULL,
DOB DATE NOT NULL,
Country VARCHAR(20) NOT NULL,
Height_cms INT NOT NULL,
Club VARCHAR(30),
Position VARCHAR(10),
Caps_for_Country INT,
IS_CAPTAIN BOOLEAN,
CONSTRAINT PID_PK PRIMARY KEY(Player_id),
CONSTRAINT CTRY_FK FOREIGN KEY(Country) REFERENCES COUNTRY(Country_Name)
);

CREATE TABLE SOCCER.MATCH_RESULTS(
Match_id INT,
Date_of_Match DATE NOT NULL,
Start_Time_Of_Match TIME NOT NULL,
Team1 VARCHAR(25) NOT NULL,
Team2 VARCHAR(25) NOT NULL,
Team1_score INT NOT NULL,
Team2_score INT NOT NULL,
Stadium_Name VARCHAR(35) NOT NULL,
Host_City VARCHAR(20) NOT NULL,
CONSTRAINT MID_PK PRIMARY KEY(Match_id),
CONSTRAINT TM1_FK FOREIGN KEY(Team1) REFERENCES COUNTRY(Country_Name),
CONSTRAINT TM2_FK FOREIGN KEY(Team2) REFERENCES COUNTRY(Country_Name)
);

CREATE TABLE SOCCER.PLAYER_CARD(
Player_id INT,
Yellow_Cards INT,
Red_Cards INT,
CONSTRAINT PLAYID_PK PRIMARY KEY(Player_id),
CONSTRAINT PID_FK FOREIGN KEY(Player_id) REFERENCES PLAYERS(Player_id)
);

CREATE TABLE SOCCER.PLAYER_ASSISTS_GOALS(
Player_id INT,
No_of_Matches INT,
Goals INT,
Assists INT,
Minutes_Played INT,
CONSTRAINT PL_PK PRIMARY KEY(Player_id),
CONSTRAINT PLAY_FK FOREIGN KEY(Player_id) REFERENCES PLAYERS(Player_id)
);

